title: Justin Abner
#logo: /assets/img/headshot_circle.png   Will need to add an assets folder with images inside
description: # Welcome! Here are some of my favorite projects showcasing my skills across different domains while utilizing various programming languages, packages, and technologies!
show_downloads: true
theme: jekyll-theme-minimal
author: 
  email: justinabner97@gmail.com
  phone: (410)-443-4376 
  
defaults:
  # _posts
  - scope:
      path: ""
      type: 
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
