title: Justin Abner
#logo: /assets/img/headshot_circle.png   Will need to add an assets folder with images inside
description: Welcome! Here are some of my favorite projects showcasing my skills across different domains utilizing various programming languages, packages, and technologies!
show_downloads: true
theme: jekyll-theme-minimal
